### ISSUE TITLE
Invalid binding of this

### ISSUE THREAD

**Issue by FractalizeR** [esnext/es6-arrow-function#12]
Arrow functions are a little different from regular ones by the binding of `this`. They do not change `this` context, so function "inherits" it from its parent context. So, I think when you compile

```
[1, 2, 3].map(n => n * 2);
```

 you should get something like

```
[1, 2, 3].map(function(n) { return n * 2; }.bind(this));
```

if I am not mistaken.

**Comment by eventualbuddha** [comment]
You are correct. However, `bind` is a drag on performance, so if we can tell that it is not needed (because `this` isn't used in the body) then we can omit it. That's what is happening here.

On an unrelated note, this project and its parent, esnext, have been deprecated in favor of [6to5](http://6to5.org/). It has more features and is faster.
